def usage():
    print ("###########################################################################################")
    print ("#  Programmer...: Carlos Alberto Schnaider                                                #")
    print ("#  Objective....: Remove some string from filename generated by SSMS                      #")
    print ("#  Date.........: 01-03-2024                                                              #")
    print ("#  Version......: 1.0.0.0                                                                 #")
    print ("#                                                                                         #")
    print ("#  Usage:  fix_sqlfiles <options>                                                         #")
    print ("#      Options:                                                                           #")
    print ("#      -t  --table          # remove Table                                                #")
    print ("#      -p  --procedure      # remove StoreProcedure                                       #")
    print ("###########################################################################################")
    

if __name__ == "__main__":
    usage()
